project:
  type: book

book:
  title: "Open Social Psychology"
  cover-image: cover.png
  author: 
    - name: "Rima-Maria Rahal"
      orcid: 0000-0002-1404-0471
      email: rima-maria.rahal@wu.ac.at
      affiliations:
        - name: Vienna University of Economics and Business; Max Planck Institute for Research on Crime, Security and Law
          address: Welthandelsplatz 1
          city: 1020 Wien
          state: Austria
  date: 2026-05-27
  downloads: [pdf, epub]
  page-footer: 
    left: |
      Open Social Psychology
    right: |
      Edited by Rima-Maria Rahal
  sidebar:
    search: true
    logo: resources/logo.png
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/rimamrahal/OpenSocialPsychology
          - text: Report a Bug
            href:  https://github.com/rimamrahal/OpenSocialPsychology/issues
  chapters:
    - index.qmd
    - howthisbook.qmd
    - howto.qmd
    - intro.qmd
    - science.qmd
    - part1.qmd
    - chapter2.qmd #Pygmalion Effect
    - chapter3.qmd #Cognitive Dissonance
    - chapter15.qmd #Implicit association Test and Attitudes
    - chapter5.qmd #Ego Depletion
    - chapter6.qmd #Feeling the Future
    - part2.qmd
    - chapter21.qmd #Conformity
    - chapter4.qmd #Obedience to Authority
    - chapter7.qmd #Social Loafing (Ringelmann Effect)
    - chapter8.qmd #Social Facilitation
    - chapter1.qmd #Pretty Privilege: Stereotypes as Self-Fulfilling Prophecies
    - chapter10.qmd #Standford Prison Experiment
    - chapter22.qmd #Social Norms
    - chapter9.qmd #Minimal Group Effect
    - chapter11.qmd #Stereotype Threat
    - chapter12.qmd #Intergroup Contact Theory
    - chapter13.qmd #Bystander Effect
    - chapter14.qmd #Social Heuristics Hypothesis
    - part3.qmd
    - chapter16.qmd #False Consensus Effect
    - chapter17.qmd #Facial Feedback Hypothesis
    - chapter18.qmd #Heat Priming-Hostile Perception Effect 
    - chapter19.qmd #Florida Priming Effect
    - chapter20.qmd #Hot Coffee Effect
    - references.qmd
    - glossary.qmd
    - summary.qmd

bibliography: references.bib
csl: apa.csl
 
format:
  html:
    theme: lux
  pdf:
    documentclass: book
    keep-tex: true
    output-file: pdf-book
    link-citations: true
    link-bibliography: true
    linkcolor: green
    citecolor: green
    header-includes:
      - \usepackage{fancyhdr}
      - \usepackage{graphicx}
      - \usepackage{eso-pic}
      - \usepackage{tikz}
      - \AtBeginDocument{\thispagestyle{empty}\begin{tikzpicture}[remember picture,overlay]
              \node at (current page.center) [yshift=1cm] {\includegraphics[width=0.75\paperwidth,height=0.9\paperheight,keepaspectratio]{resources/cover.png}};
              \end{tikzpicture}\clearpage}
  epub: 
    cover-image: cover.png

editor: source

comments:
  hypothesis: true
  
callout-appearance: simple
callout-icon: false
