# [Social Facilitation]{style="color: #004b23"}

[written by Dearbhaile Vaughan (original draft), Kate Grady (original draft), Cillian McHugh (revision), and Siobhán M. Griffin (revision)]{style="color: gray;"}

## The Classic

Social Facilitation is a theory that posits that one will perform better on a task when it is completed in the presence of others. In 1898, Norman Triplett demonstrated that when people complete a task in competition with another person, they perform better on the task compared to completing the task alone [@Triplett_1898]. This seminal experiment sparked a rich literature on the concept of “social facilitation,” a term which was coined some 20 years later by @Allport_1954 – the idea that the mere presence of others can lead to improvements in performance [@Aronson-et-al_2005; @Bond-Titus_1983].

> [#definition]{#def-socialfacilitation style="color: orchid"} Social Facilitation
>
> This theory proposes that the mere presence of others will positively affect performance on a task.

Triplett’s seminal study [-@Triplett_1898] was the result of perceived trends he observed in cyclists. Triplett noticed that in both paced and competitive settings, cyclists tended to cycle faster when accompanied by others. He had a multitude of theories as to why this was, including both physical and psychological hypotheses. One theory was that of the ‘Encouragement Theory’, where the presence of a friend would cheer on and “keep the [participant's] spirits up.” Other theories included: ‘Shelter Theory’ – the lead cyclist creates shelter from the wind making it easier for those behind to cycle; ‘Suction Theory’ – a vacuum is created by “suction exertion” from the cyclist in front; and ‘Theory of Hypnotic Suggestions’ – that a hypnosis effect is created by the wheels of the bicycle in front, and this leads to better performance.

To test his theory, Triplett designed a lab-based study to examine if the presence of a competitor stimulates competition arousal, which he called “dynamogenic factors.”

> [#definition]{#def-dynamogenesis style="color: orchid"} Dynamogenesis
>
> An increase in the mental or motor activity of an already functioning bodily system that accompanies any added sensory stimulation (Merriam-Webster).

For the experiment, two fishing reels were attached to a table to create a type of pulley system that moved a flag around a four-metre course. Children were invited to participate in this study. After a practice period to allow children to become accustomed to the machine, they completed six trials alternating between performing alone and performing in competition with another child. There were rest periods in between each trial to avoid the effects of fatigue. Performance was defined as the time taken to complete one trial (four laps of the course) as measured by a stopwatch. The results showed that children performed better (i.e., completed the laps faster) during the competition/together trials compared to the alone trials. However, some variation was noted where some children, described as “overstimulated,” performed slower on the together trials.

> [#yourturn]{style="color: green"}
>
> Can you think of how the factors such as (i) age variability, (ii) potential differences in practice times, (iii) lack of clarity around the rest periods, and (iv) reporting on data from a subsample of 40 participants (out of 225) may have potentially affected the observed findings?

Triplett’s findings and theory posited that competition stimulates performance (competitive coaction), but subsequent researchers focused on a broader application of this idea - that the mere presence of another person would improve performance, competitive or not.

## The Aftermath

Subsequent research focused on social facilitation across a number of different social pressure contexts, including having an observer or audience present, having an evaluative observer or audience, a non-competing co-actor, and similar to Triplett’s study - in the presence of a competing co-actor [@Dashiell_1930]. Some research has highlighted the importance of task complexity. For instance, @Zajonc_1965 examined social facilitation in a sample of cockroaches, showing that social presence enhances performance on simple tasks but hinders performance on more complex tasks (completing a runway vs completing a maze). Based on behaviour theory [@Hull_1943; @Spence_1956], Zajonc postulated that “generalized drive” is what motivates habits. According to Zajonc’s theory, having other people around increases generalized drive, which makes it easier for habitual dominant responses to occur. While for more complex tasks the dominant response may not be the correct response [@Bond-Titus_1983; @Zajonc_1965]). However, a replication of Zajonc’s study did not fully replicate this effect; in simple and complex tasks, the cockroaches performed more slowly when other cockroaches were present [@Halfmann-et-al_2020].

> [#definition]{#def-generalizeddrive style="color: orchid"} Generalized Drive
>
> The presence of others leads to an increase in generalized drive, thus facilitating habitualised dominant responses.

Although @Zajonc_1965 believed that the mere presence of others is the necessary ingredient in producing social facilitation effects, other researchers disagreed. Cottrell et al. [-@Cottrell_1972; -@Cottrell-et-al_1968] argued that social facilitation occurs when a third party is perceived to be observing the performance, but that mere presence (without observation) was not sufficient to produce social facilitation effects. It is the expectation of evaluation that increases drive, and thus influences performance [@Bond-Titus_1983; @Cottrell_1972; @Weiss_Miller_1971].

There are a number of theoretical explanations to explain how, why, and when social facilitation effects occur [for reviews see @Bond-Titus_1983; @Seitchik-et-al_2017]. Some key theories include:

- *Distraction-conflict theory:* the idea that the presence of others is distracting and takes up attention resources which may lead to cognitive overload, reducing attention on the task [@Baron_1986; @Sanders-et-al_1978]. This may result in dominant responses facilitating performance when the task is simple and requires attention to a small number of cues, but when the task is more complex or demands attention to a larger number of cues performance may be hindered.
- Muller and Butera's [-@Muller_Butera_2007] *Integrated distraction-conflict theory and Social comparison theory* [@Festinger_1954]; e.g., that people compare their own skills to other people’s skills), and proposed that when in a co-action setting people can experience self-evaluation threat which may increase their attentional focus, in particular when a co-actor is seen to be superior, increasing drive and thus performance.

> [#definition]{#def-distractionconflicttheory style="color: orchid"} Distraction-Conflict Theory
>
> This theory states that attentional conflict, a type of response conflict regarding what attentional response one should make, can arise when the social presence of others (co-actors or an audience) is distracting, at least when the task is attention demanding. The actor may then be at risk of cognitive overload as a result of this conflict, which would ultimately lead to a limitation in their ability to focus on the task.

> [#definition]{#def-socialcomparisontheory style="color: orchid"} Social Comparison Theory
>
> According to the social comparison theory, people are motivated to assess their own beliefs and skills by comparing them to external images. These images can be comparisons to other people or a reference to physical reality. Individuals have a tendency to view images portrayed by others as accessible and realistic and subsequently make comparisons between themselves, other people, and these idealized images.

### Practical Implications Arising from Triplett’s Original Study

Research on social facilitation effects has highlighted its practical implications in real-world settings. For example, @Anderson-Hanley_et_al_2011 demonstrated that adults riding on stationary bikes with virtual reality equipment exercised more when a competitive fictional character was introduced compared to cycling alone (but only if they scored highly on self-reported competitiveness). Furthermore, people have been found to consume more food [@deCastro_1994], donate more money [@Izuma-et-al_2010], and spend more money [@Sommer-et-al_1992], when with other people compared to being alone. However, sometimes the presence of another is seen to have detrimental effects. For instance, an analysis of archival data demonstrated that learner drivers who took their driving test with another individual awaiting their test present were more likely to fail than those who took the test without an observer [@Rosenbloom-et-al_2007].

> [#yourturn]{style="color: green"}
>
> Can you think of a time when you performed worse on a task because there was another individual present? And can you think of a time when you performed better on a task when there was another individual present?

### A Reanalysis of Triplett’s Data

Since 1898, more advanced statistical methods are now at researchers' disposal. @Strube_2005 reanalysed Triplett’s [-@Triplett_1898] data, exploring both within-person differences in alone vs. together conditions (within-subjects tests) and differences between people across the alone vs. together trials (between-subjects tests). This re-analysis demonstrated that in general performance in the competition trials was better than the alone trials (between-subjects test); however, this was not a statistically significant difference. Likewise, looking at within-participant variation, there was only a marginally significant effect for performing better on the competition trials compared to a person’s alone trials.

### Replication of the Original Study

A recent pre-registered study directly replicated Triplett’s [-@Triplett_1898] original experiment, addressing some of the limitations mentioned earlier – namely the small (and underpowered) sample size, standardization of experimental trials and rest periods, as well as examining if gender moderated the effects [@McHugh_et_al_2025]. This analysis of >400 children aged 7-13 years, who were age- and gender-matched, demonstrated that participants completed the task quicker during the together trials compared to the alone trials. Gender moderated this effect, with females completing the task faster on average, and the social facilitation/competitive co-action effect was stronger for females. This replication provides support for Triplett’s original findings.

## Conclusion

Overall, it appears that in some settings the presence of another (whether evaluative or non-evaluative, or co-actor, competitor or observer) affects performance. Often the presence of another appears to facilitate performance or dominant response tendencies, but the conditions under which this occurs need further examination as sometimes the presence of another hinders performance. While Triplett focused on competitive coaction effects, which was later termed social facilitation (and gave rise to this literature), it is important to note that the theory of social facilitation relates to mere presence of another individual affecting performance. Triplett’s [-@Triplett_1898] experiment and the more recent replication [@McHugh_et_al_2025] are not able to disentangle if the effects on performance are truly due to mere presence of another person (i.e., social facilitation) or due to competition.

> [#yourturn]{style="color: green"}
>
> Why do you think it matters whether performance depends on mere presence of others or if others need to be co-actors and/or competitors? 

More research is needed to fully understand what is driving the observed effects. Think back to the practical implications section of this chapter. If we know under what conditions mere presence affects performance (positively and negatively), or under what conditions having someone engaged in the same task as us (co-actor) or even competing against us, then this can help us design optimal environments for a range of performance-based activities, such as learning and exercise/sport.
