# [Power Posing]{style="color: #004b23"}

[written by Sarah von Götz (original draft), and Hilmar Brohmer (revision)]{style="color: gray;"}

## The Classic

Imagine you are nervous before a presentation or job interview. Wouldn’t it be great if there was a quick and simple solution to make yourself feel confident and powerful, potentially even on a hormonal level, and it only takes a couple of minutes of your time? Wouldn’t that be great? This is the promise of the effects of *power posing*, which is the practice of standing in a “powerful pose” (imagine Wonder Woman) for a couple of minutes to change how powerful you feel.

> [#yourturn]{style="color: green"}
>
> If you feel up to it, try it yourself! Set a timer for one minute and stand up straight and take up as much space with your body as you can. After the minute is over, take a second to notice how you feel. Do you feel more confident or powerful than before? Maybe even less stressed?

> [#definition]{#def-powerposing style="color: orchid"} Power Posing 
>
> Behavioral technique where a person assumes and holds an open pose that is associated with being powerful through taking up space in a room. This is intended to make you feel more confident and powerful.


This practice was first suggested in a 2010 paper by Dana Carney, Amy Cuddy and Andy Yap [@carney_power_2010]. The claim of this paper was that humans, like other animals, express power and dominance through their posture, with high power being expressed by open and expansive postures and low power (or obedience) being expressed by closed, contractive postures, where they make themselves small. Following the idea of embodiment, the authors expected that such poses would have effects on participants’ feelings, behavior and their physiology.

> [#definition]{#def-embodiment style="color: orchid"} Embodiment 
>
> The idea that the mind and body influence each other, so that the body plays a significant role in shaping how we think and feel.

In their original experiment the authors had 42 participants, who either assumed two “high-power” poses, such as sitting stretched out with their hands behind their head and their feet on a desk, or two “low-power” poses such as standing with both arms wrapped around themselves. Each pose was held for a minute. Afterwards, participants were first presented with a risk assessment task, where they could either keep 2$ or gamble them on a higher reward. The authors also asked participants how powerful they felt on a rating scale from 1 (not at all) to 4 (a lot). Additionally, they  measured participants’ cortisol (a hormone associated with stress levels) and testosterone (a hormone assumed to be connected to dominant behaviors) before and after assuming their poses. 

> [#definition]{#def-cortisol style="color: orchid"} Cortisol 
>
> Cortisol is often called the “stress hormone”, since it regulates your body’s response to stress. During stressful events it spikes and activates the body’s fight or flight response, meaning that you are on high alert to deal with a potential threat. 

> [#definition]{#def-testosterone style="color: orchid"} Testosterone 
>
> Testosterone is a hormone mainly associated with reproduction and physical development. It might be associated with certain behaviors such as competitive behavior, dominance, or aggression, although this depends on the situation and the individual. For a more recent article on the influence of hormones on psychology see @botzet_behavioural_2024.

As the authors hypothesized, the high-power poses seemed to cause an increase in testosterone and a decrease in cortisol, while the low-power poses showed a decrease in testosterone and an increase in cortisol. Participants in the high-power group were also more likely to take the gambling risk and subjectively felt more powerful and “in charge”. The authors concluded that this could have substantial implications for everyday life, since assuming certain poses seemed to significantly change people’s physiology, mental state, and feelings. This means that if you can change how powerful you feel, your behavior, and even your hormones through your body position, you may be able to use this to your advantage. The hormonal changes would mean that, because of the lowered cortisol, you feel less stressed, and that the higher testosterone levels make you behave more dominantly. The authors therefore concluded that their results imply that people can use power posing to “fake it till you make it” in situations that require power, such as job interviews, disagreeing with their bosses, public speaking, or taking profitable risks. 

## The Aftermath

Power posing very quickly entered the public sphere following a 2012 TED Talk by the original study author Amy Cuddy titled Your Body Language May Shape Who You Are, which to this date is one of the most watched TED-talks of all time [@cuddy_your_2012]. Power posing was also widely reported in popular media, and Cuddy later published a self-help book based on the idea that adopting confident body language could improve performance and well-being [@cuddy_presence_2015].

However, an independent replication study in 2015 [@ranehill_assessing_2015-1] that had a larger sample of N = 200 and a more controlled research design, where the researchers were blind to the conditions they assigned their participants to, could only replicate the finding that participants subjectively reported higher feelings of power in the power posing condition, but no statistically significant hormonal changes or behavioral differences were found. 

Following this, methodologists took note of the original study and started criticizing the growing power posing literature as suffering from small sample sizes, low statistical power, and likely selective reporting [@simmons_power_2017]. Moreover, one of the original study authors, Dana Carney, released a statement regarding the original study that she did not believe the effects of power posing were real [@carney_my_2016].

> [#definition]{#def-statisticalpower style="color: orchid"} Statistical Power 
>
> Statistical power is the probability that a study will detect an effect (a real relationship) if that effect actually exists.

A more recent meta-analysis based on 88 studies involving 9,779 participants [@korner_dominance_2022] found effects of body position on self-report measures (such as “feeling powerful”) but no reliable effects on physiological outcomes. There was some evidence for behavioral effects, but the authors also found that these findings were likely influenced by publication bias. To this day, it is also still unclear whether high power poses or low power poses drive the effect, since most studies did not have a neutral pose control group.

> [#definition]{#def-publicationbias style="color: orchid"} Publication Bias 
>
> The phenomenon that research findings are more likely to be published when the results are statistically significant.

## Conclusion

The original claim that power posing changes people’s physiology, mood and behavior has become somewhat of an example of the replication crisis in social psychology, where findings that initially appeared compelling sometimes are “too good to be true”. The original claim of hormonal changes and risk-taking behavior did not hold up to replication [@ranehill_assessing_2015-1] and even one of the original study authors, Dana Carney, stated that she no longer believes in the effects of power posing [@carney_my_2016]. There is, however, some evidence that adopting expansive body postures increases people’s self-reported feelings of power [@korner_dominance_2022]. However, because these findings rely on self-report measures, they may be susceptible to demand effects, which is the subject of an ongoing scientific debate. 

> [#definition]{#def-demandeffects style="color: orchid"} Demand Effects 
>
> Sometimes people participating in an experiment interpret what the experiment is supposed to measure and what the researcher expects. This can lead to them consciously or subconsciously changing their behavior to what they think is expected of them.

Overall, the best available evidence suggests that power posing may influence how powerful people report to feel, but there is little convincing evidence that it reliably changes hormones or produces broad changes in behavior.
