# [Pretty Privilege: Stereotypes as Self-Fulfilling Prophecies]{style="color: #004b23"}

[written by Antonio Scholz (original draft), Alma Jeftic (revision), and Xinkai Du (revision)]{style="color: gray;"}

## 1. The Classic

Did you realize that people who are perceived to be more attractive might also get treated better? What seems like it might be a nagging suspicion to some has also piqued the academic interest of social psychologists. This research deals with body privilege or pretty privilege, the idea that physical (normative) attractiveness is related to having social advantages in multiple dimensions: job success, income, friendships, educational attainment, politics, and even criminal procedure.

> [#definition]{#def-privilege style="color: orchid"}  Privilege  
> 
> Privileges describe social advantages people receive because of their perceived membership to a certain group (e.g., the group of pretty people, or the group of tall people).

> [#yourturn]{style="color: green"}  
> Why do you think people who are “pretty” might be treated more favorably?

This research argues in part that physical attractiveness is used as a cue for other positive attributes such as intelligence, or kindness. This is sometimes referred to as the halo effect, where the halo of attractiveness “spills over” to other facets of person perception [@lucker_strength_1981]. Some evolutionary theories argue this is the case because attractiveness is perceived to signal evolutionary fitness [@forgas_halo_2016].

> [#definition]{#def-haloeffect style="color: orchid"}  Halo Effect  
> 
> A cognitive bias where a certain characteristic overshadows the overall impression formed. For instance, someone who is perceived as physically attractive may also be thought of as kind or smart.

> [#yourturn]{style="color: green"}  
> How do you think conventional attractiveness is perceived?

The study by @snyder_social_1977 on the self-fulfilling nature of social stereotypes and its replication attempt by @andersen_sex_1981 explore gender stereotypes in interactions between two people.

In the original study, @snyder_social_1977 investigated how social stereotypes influence interpersonal behavior, focusing on self-fulfilling prophecies, i.e. a prediction that brings about its own fulfillment.

> [#definition]{#def-stereotype style="color: orchid"}  Stereotype  
> 
> Stereotypes are beliefs about people held because of their membership in a social group.

> [#definition]{#def-selffulfillingprophecy style="color: orchid"}  Self-Fulfilling Prophecy  
> 
> A self-fulfilling prophecy suggests that the probability of an event occurring can be increased solely by the expectation of that event (Merton, 1948).

Male participants interacted with female participants via phone calls, to get to know each other. The male participants received a photograph, ostensibly showing their female interaction partners. However, these photos were experimentally manipulated and showed other women who had previously been rated to be either the most physically attractive or the least attractive.

After receiving the photos, but before interacting with their female interaction partners, the male participants who had received a photo of a highly attractive woman expected their interaction partner to be more sociable, humorous and socially capable than those who had received a photo of a less attractive woman. In other words, the male interaction partners formed a (potentially false) impression of their female interaction partners’ physical attractiveness that carried over (halo effect) to forming an expectation that they would display other positive characteristics.

Female interaction partners did not know about these photos, and did not receive photos of their male interaction partners. When the pairs of participants interacted, their interactions were recorded and later rated by independent observers. These observers rated that women matched with a man who received a photo of a physically highly attractive supposed interaction partner also behaved in line with this partners’ expectation: more warmly, more socially, and so on. These findings supported the idea that social perceptions are determined by self-fulfilling prophecies. Because they were perceived to be more attractive, these participants were treated more favorably.

The results confirmed those of an earlier study by @dion_what_1972. They, too, found that “what is beautiful is good” (ibid., p. 285). This study showed that more physically attractive people were assumed to have happier social lives and more professional success.

> [#yourturn]{style="color: green"}  
> In reality usually both participants of such interactions have expectations and stereotypes. What would that mean for the self-fulfilling nature of these expectations?

## 2. The Aftermath

@andersen_sex_1981 attempted to replicate and extend the findings by examining how individuals who differ in gender type and androgyny respond to physical attractiveness in interactions with two partners. This time, not only gender-typical but also androgynous male and female participants conducted acquaintance phone calls with supposedly attractive and unattractive members of their own and the opposite gender.

> [#definition]{#def-androgyny style="color: orchid"}   Androgyny 
> 
> A gender expression combining characteristics traditionally associated with masculinity and femininity, or expressing neither.

As expected, people who fit more traditional gender roles responded more positively to potential partners who had been rated by independent observers as physically attractive than to those rated as less attractive. However, this pattern was different for androgynous participants. There was no evidence that androgynous men judged potential partners based on physical attractiveness. Androgynous women showed the opposite pattern: they rated the supposedly less attractive partners as more socially appealing than the supposedly attractive partners. This finding challenged the idea that physically attractive people are always seen as more desirable.

While the study by @snyder_social_1977 purported to provide solid evidence of the self-fulfilling nature of social stereotypes, the replication by @andersen_sex_1981 introduced nuances in terms of individual differences. The results indicated that androgynous individuals may exhibit different patterns of response to physical attractiveness compared to individuals displaying gender-typical looks. The replication experiment demonstrates that more than one factor needs to be considered, as social perception and resulting behavior is influenced multivariately.

In the following decades, research on pretty privilege continued to demonstrate, overall, that people place a premium on physical attractiveness. For instance, @mobius_why_2006 showed in an experiment imitating the labor market that physically more attractive workers were (wrongly) considered to be better at the experimental task by employers. Physically more attractive workers were more confident, and had better social skills, which in turn led them to earn more money after negotiating with their employers than less attractive workers. In an observational study of sentencing decisions in criminal trials [@stewart_ii_defendants_1980], the defendants’ physical attractiveness was correlated with the severity of the punishment: More attractive defendants received less severe sentences. Studying perceived political experience, @palmer_halo_2016 showed that people rated as more attractive were also perceived to be more politically knowledgeable, and more persuasive in political discussions. Physical height, a feature often considered to contribute to attractiveness, has been linked with social esteem and success in the workplace and increased income [@judge_effect_2004].

> [#yourturn]{style="color: green"}  
> Is pretty privilege a cross-culturally stable phenomenon?

A large-scale replication study assessed pretty privilege interculturally [@batres_examining_2023]. Using data collected in 45 countries, this study demonstrated that male and female faces rated as more attractive were also rated to be more confident, emotionally stable, intelligent, responsible, sociable, and trustworthy. Put differently, this research demonstrated a robust halo effect of physical attractiveness, across cultures.

> [#yourturn]{style="color: green"}  
> In the age of AI image manipulation and beauty filters, do you think pretty privilege still exists?

A recent study showed that AI-processed images to which a beauty filter was applied were rated as both more attractive, and as more intelligent and trustworthy than the same photo without the filter applied [@gulati_what_2024]. Consequently, the robust effect of pretty privilege seems to persist.

Other research, however, suggests that being perceived as physically attractive is not always associated with privilege. Physical attractiveness may also be associated with socially undesirable characteristics like being vain [@dermer_when_1975], materialistic or sexually permissive (Bassili, 1981). When physical attractiveness was related to the crime committed (swindle, but not burglary), more attractive defendants received larger hypothetical punishments [@sigall_beautiful_1975]. For women holding a management position, being perceived as more attractive was a disadvantage in performance evaluations and for getting promoted or a pay raise [@heilman_being_1985].

## 3. Conclusion

The comparison between the original study by @snyder_social_1977 and the research that followed underscores the multifaceted nature of social perception and interpersonal behavior. Although the concept of pretty privilege appears to be robust, the role of individual differences in shaping responses to social stimuli deserves consideration. In particular, pretty privilege should be seen in the context of intersectionality: Who is perceived to be attractive, and how this attractiveness may relate to privilege, is also a matter of intersecting social categories such as race, class, or disability. Similarly, the situational circumstances under which people are being judged could even turn pretty privilege into a pretty disadvantage. Overall, the evidence on the pretty privilege phenomenon warrants a nuanced perspective that recognizes the interplay of stereotypes, individual characteristics, and situational factors to understand the complexity of social interactions.
