# [Glossary]{style="color: #004b23"} {.unnumbered}

#### [Adversarial Collaboration](chapter6.qmd#def-adversarialcollaboration)
A research project where researchers have different views and predictions, or support opposing theories.

#### [Agentic State](chapter4.qmd#def-agenticstate)
The agentic state is a psychological condition where individuals see themselves as agents executing the wishes of an authority figure, thereby absolving themselves of responsibility for their actions.

#### [A priori power analysis](chapter11.qmd#def-apriorianalysis)
Before a study is conducted ("a priori"), researchers use a statistical method to estimate the minimum sample size needed to reliably detect a specified effect size. Often, researchers aim for tests that have at least 80% power, that means that the tests can correctly reject a null hypothesis when it is false in at least 80% of cases. This analysis guides the determination of the planned sample size.


#### [Attitude](chapter15.qmd#def-attitude)
The cognition, affect and behavioral tendencies towards a certain object.

#### [Availability Heuristic](chapter16.qmd#def-availabilityheuristic)
A mental shortcut where people estimate the likelihood of an event based on how easily examples come to mind, which can lead to overestimating rare but memorable occurrences.

#### [Betrayal Aversion](chapter24.qmd#def-betrayalaversion)
The tendency for people to feel greater harm or distress from a negative outcome caused by another person's deliberate choice than from an equally bad outcome caused by chance or an impersonal source.


#### [Bias](chapter16.qmd#def-bias)
A systematic distortion of perception or judgment.

#### [Bystander Effect](chapter13.qmd#def-bystandereffect)
When others (bystanders) are thought to be present, this delays or even fully undermines prosocial behavior.


#### [Causal Relationship](chapter14.qmd#def-causal)
A causal relationship refers to the situation when an event is the direct result of a preceding event. In the research context, causal relationships occur when the manipulation of an independent variable causes and explains the observed effects in a dependent variable that would otherwise not occur. Conversely, correlation is a statistical measure that describes the magnitude and direction of the relationship between two or more variables. In contrast to causal relationships, correlation does not imply that changes in the independent variable will automatically lead to and explain the observed effects in the dependent variable.

#### [Ceiling Effect](chapter4.qmd#def-ceilingeffect)
A ceiling effect is said to occur when a high proportion of subjects in a study have maximum scores on the variable.


#### [Cherry-Picking](chapter12.qmd#def-cherry-picking)
Reporting only the data, outcomes, or time frames that support one’s hypothesis while ignoring or dismissing those that do not. This makes the story or articles simpler and might make them more publishable, but provides a distorted view of the evidence.

#### [Cognition](chapter3.qmd#def-cognition)
Cognitions can be thought of as bits of knowledge, such as opinions, attitudes, or beliefs about the world, about oneself or one’s behavior. If two cognitions are relevant to each other, but the opposite of one follows from the other, these cognitions are said to be inconsistent.

#### [Cognitive Dissonance](chapter3.qmd#def-cognitivedissonance)
Cognitive dissonance describes the discomforting state that people experience when they hold cognitions that are relevant to each other but inconsistent with each other—meaning that one bit of knowledge suggests the opposite of another bit of knowledge.


#### [Conceptual Replication](chapter17.qmd#def-conceptualreplication)
A study that aims to recreate the gist of a prior study without using an identical procedure. These studies often aim to explore boundary conditions, the influence of specific variables, or aim to broaden and extend a certain finding.

#### [Confederate](chapter4.qmd#def-confederate)
A confederate is a person who is secretly working with the experimenter and plays a scripted role in the study.

#### [Confederate](chapter13.qmd#def-confederate)
In some experiments, researchers are interested in the behavior of participants given very specific social settings, and very specific behavior of others. Because it can be difficult to observe these settings in a naturally occurring environment - particularly if they also need to be varied systematically to conduct an experiment - sometimes confederates are engaged to carry out these specific behaviors. In other words, they are not real participants in the study, they are hired helpers who act in accordance with the experimental setup.


#### [Confirmatory Study](chapter6.qmd#def-confirmatorystudy)
A research investigation that tests (often preregistered) hypotheses derived from theory or prior empirical research.

#### Contact Interventions ([Intergroup Contact Theory](chapter12.qmd#def-contactinterventions), [Hot Coffee Effect](chapter20.qmd#def-contactinterventions))
Carefully tailored interventions that apply intergroup contact in real-world settings to try and reduce prejudice among social groups.

#### [Construct Validity](chapter15.qmd#def-constructvalidity)
The extent to which a test measures the theoretical construct or concept it is intended to measure.

#### [Correlation](chapter13.qmd#def-correlation)
Two variables are said to correlate when there is a relationship between the two, where one increases or increases as the other does, too, or one increases as the other falls. The degree to which these variables move together is expressed as the size of the correlation coefficient, which ranges from 0 (no correlation) to abs(1) (perfect correlation).


#### [Demand Characteristics](chapter10.qmd#def-demandcharacteristics)
These are cues in an experiment that give away what the researcher expects, which can lead participants to change their behavior to fit those expectations.

#### [Descriptive Norms](chapter22.qmd#def-descriptivenorms)
Descriptive norms refer to what people believe is the description of group behavior (decisions based on limited information may generate misperceptions; thus, perceived norms do not necessarily reflect actual group behavior), whose main influence on behavior is of informative nature.


#### [Discriminant Validity](chapter15.qmd#def-discriminantvalidity)
The extent to which a test is unrelated to measures designed to assess theoretically distinct constructs.

#### [Dual Process Theories](chapter14.qmd#def-dualprocess)
A set of theories that distinguish human thought into two sub-systems: a fast, intuitive system (System 1) and a slow, deliberate system (System 2). The former appears to be independent of cognitive control, whereas the latter is effortless and relies on working memory and cognitive capacity.


#### [Dynamogenesis](chapter8.qmd#def-dynamogenesis)
An increase in the mental or motor activity of an already functioning bodily system that accompanies any added sensory stimulation.

#### [Effect Size](chapter11.qmd#def-effectsize)
In statistics, the effect size refers to a value that indicates the magnitude of the relation between independent and dependent variable. In factorial designs (experiments), the effect size gives us information on how large the difference between groups is.

#### [Effect Size](chapter16.qmd#def-effectsize)
A quantitative measure of the magnitude of a phenomenon, used to assess the practical significance of research findings.

#### [Editorial](chapter2.qmd#def-editorial)
An introductory article written by the editors of a special issue in an academic journal. It outlines the purpose, scope, and significance of the special issue, provides an overview of the included articles, and often highlights key themes, trends, or gaps in the research field.

#### [Ego Depletion](chapter5.qmd#def-egodepletion)
A concept that describes willpower as a limited resource that can be used up (depleted).

#### Experiment ([Intergroup Contact Theory](chapter12.qmd#def-experiment), [Hot Coffee Effect](chapter20.qmd#def-experiment))
A study where researchers deliberately manipulate one or more variables and randomly assign participants to different conditions. Random assignment helps ensure the groups are similar before the intervention, so differences in outcomes are more likely to be caused by the manipulation rather than by pre-existing differences.

#### [False Consensus Effect](chapter16.qmd#def-falseconsensus)
A cognitive bias where individuals overestimate the extent to which others share their beliefs, preferences, and behaviors.

#### [Foot-in-the-door](chapter4.qmd#def-footinthedoor)
Foot-in-the-door is a two-step procedure for enhancing compliance in which a minor initial request is presented immediately before a more substantial target request. Agreement to the initial request makes people more likely to agree to the target request than would have been the case if the latter had been presented on its own.

#### [Forced-Compliance Paradigm](chapter3.qmd#def-forcedcomplianceparadigm)
A very early paradigm of cognitive dissonance initially stemming from the persuasion field where participants are asked to perform a discrepant behavior (mainly a speech or essay), being more or less incentivized for doing it. Classic studies [e.g., @festinger1959cognitive] report counter-intuitive results showing more attitude change when paid a small amount of money in comparison to a bigger amount. This contradicted predominant theoretical frameworks at the time, such as the reinforcement theory [@skinner1958reinforcement], which would have predicted that people adjust their attitudes especially when they receive a high reward.

#### [Gender Inclusive Language](chapter23.qmd#def-genderinclusivelanguage)
Gender inclusive language is a tool of grammatical structure to transform the way we think, eliminating gender biases and ensuring visibility, belonging, and identity of all people.


#### [Gender Star](chapter23.qmd#def-genderstar)
Gender star is an inclusive typography resource ( :, \*, @, x, e) that breaks away from traditional linguistic structures. Its function is to simultaneously make men, women and diverse identities visible within a single word, challenging the norm of the generic masculine.

#### [Generalized Drive](chapter8.qmd#def-generalizeddrive)
The presence of others leads to an increase in generalized drive, thus facilitating habitualized dominant responses.

#### [Generic Masculine](chapter23.qmd#def-genericmasculine)
The generic masculine is a linguistic form that uses the masculine grammatical gender to designate men, women, mixed groups, and unspecified individuals, often reducing visibility and inclusion of women and non-masculine identities.


#### [Group Cohesion](chapter7.qmd#def-groupcohesion)
Group cohesion describes how connected and committed people feel to the group.


#### [Groupthink](chapter10.qmd#def-groupthink)
A psychological phenomenon that occurs when members of a group strive for consensus and harmony, often at the expense of critical thinking or considering alternative options.


#### [Habituation](chapter6.qmd#def-habituation)
Habituation is a phenomenon where we get used to a stimulus, following its repeated exposure. As a consequence, the reaction to the stimuli is reduced.

#### [HARKing](science.qmd#def-harking)
HARKing is Hypothesizing After the Results are Known and where a lucky guess looks like a solid scientific theory. It violates the principle that a theory should be able to *predict* behavior, not just describe it after the fact.

#### [Heuristic](chapter14.qmd#def-heuristic)
Heuristics refer to simple processes that assist individuals to identify adequate, but imperfect, answers to complex questions [@kahneman_thinking_2011].


#### [Implicit Association Test](chapter15.qmd#def-implicitassociationtest)
A reaction-time task that measures the strength of automatic associations between concepts (e.g., flowers and positivity) by comparing how quickly people classify paired categories. Faster responses indicate stronger underlying associations.

#### [Implicit Attitude](chapter15.qmd#def-implicitattitude)
An enduring mental disposition toward something that is not consciously identified and of which a person may lack awareness.

#### [Implicit Social Cognition](chapter15.qmd#def-implicitsocialcognition)
The automatic, unconscious mental processes that influence how we perceive, evaluate, and interact with others.

#### [Incongruent Association](chapter15.qmd#def-incongruentassociation)
A mental relationship between two objects or concepts characterized by lack of harmony or misalignment.

#### [Induced-Compliance Paradigm](chapter3.qmd#def-inducedcomplianceparadigm)
An evolution of the forced-compliance paradigm [@linder1967decision] where participants have to perform a behavior that is inconsistent with their attitudes—typically writing or delivering a counter-attitudinal essay. In this version, all participants engage in the discrepant task, but they differ in the justification provided. Half are explicitly told they have a free choice in performing the task (freedom condition), while the other half are simply asked to do it, as in the original forced-compliance paradigm. The key difference lies in the source of justification: an external incentive in the traditional condition, versus perceived freedom of choice in the revised one. The classic results show a greater change in the attitude in the choice condition (high choice) compared to the control condition (low choice).

#### [Ingroup](chapter13.qmd#def-ingroup)
One’s own social group (as opposed to other groups, called outgroups).

#### [Injunctive Norms](chapter22.qmd#def-injunctivenorms)
Injunctive norms refer to what people believe a group approves or disapproves of, -the ought-, whose influence is manifested through the group’s normative pressure.


#### Intergroup Bias ([Intergroup Contact Theory](chapter12.qmd#def-intergroupbias), [Hot Coffee Effect](chapter20.qmd#def-intergroupbias))
Tendency to favour one’s own social group (ingroup) over other groups (outgroups), which often leads to negative attitudes or behaviours toward outgroup members.

#### [Internalized Norms](chapter22.qmd#def-internalnorms)
An internalized norm consists of a social expectation that a person has incorporated into their beliefs and values. Thus, when a norm is internalized, it influences behavior without relying on external social pressure.


#### [Intuitive Behavior](chapter14.qmd#def-intuitivebehavior)
Behavior that occurs through automatic, prepotent and effortless cognitive operations. Commonly referred to as “System 1”, these mental operations are fast, associative and hard to control (Kahneman, 2002; Stanovich & West, 2000).

#### [Meta-Analysis](howto.qmd#def-metaanalysis)
An analysis that brings together evidence from several individual studies or experiments to estimate an overall effect across the available evidence.


#### Meta-analysis ([Intergroup Contact Theory](chapter12.qmd#def-meta-analysis), [Hot Coffee Effect](chapter20.qmd#def-meta-analysis))
A statistical technique that combines the results of multiple independent studies to estimate an overall effect. Meta-analyses can reveal patterns across a large body of research, but the quality of their conclusions depends on the quality and comparability of the included studies.

#### [Meta Analysis](chapter13.qmd#def-metaanalysis)
A meta analysis is a study that combines the results of many studies to assess the overall evidence regarding a research question.


#### [Minimal Group Effect](chapter9.qmd#def-minimalgroupeffect)
An inclination to favor one's own group even when group membership is weak or superficial, there is no history of intergroup conflict, and there is a lack of member interaction or conflicting interests.


#### [Moderator](chapter12.qmd#def-moderator)
A variable that modifies the relationship between independent and dependent variables.

#### [Motivation](chapter7.qmd#def-motivation)
Motivation encompasses internal and external factors that initiate and sustain behavior in service of a goal.


#### [Multi-Lab Study](chapter5.qmd#def-multilabstudy)
A research project in which researchers working at several different locations (laboratories) implement the same experimental design and then analyse the data together.

#### [Multi-laboratory Study / Many-labs Study](chapter23.qmd#def-multilaboratory)
A teamwork approach where researchers from different institutions follow the same protocol to run the same experiment and assess whether results replicate across sites.


#### [Multimethod Study](chapter15.qmd#def-multimethodstudy)
Research that employs two or more distinct methods.

#### [Norms](chapter10.qmd#def-norms)
These are shared rules or expectations within a group about how members should think, feel, or behave. They guide behavior by defining what is considered acceptable or unacceptable in that social context.

#### [Obedience](chapter4.qmd#def-obedience)
Obedience is the act of following orders or instructions from an authority figure, often without questioning the morality or consequences of those actions.


#### [Observational Research](chapter12.qmd#def-observationalresearch)
A study design where researchers measure variables as they naturally occur, without manipulating them. Observational studies can reveal associations between variables but cannot, on their own, establish that one causes the other.


#### [Open Science](intro.qmd#def-openscience)
An overhead term for a number of practices to make research more transparent, such as making the data a research project is based on available to others.

#### [Orbicularis Oris Muscles](chapter17.qmd#def-orbicularisoris)
These are circular muscles around the mouth that close the lips and produce puckering, as in kissing or whistling.


#### [Paradigm](chapter3.qmd#def-paradigm)
Within Kuhn’s [-@kuhn1962structure] tradition, a paradigm transcends mere methodological procedure, constituting instead a foundational scientific framework that combines theoretical principles, methodological standards, and empirical expectations. This comprehensive system guides scientific practice by providing explanatory models and predicting experimental outcomes. The paradigm's coherence depends on the alignment of these elements—when empirical results contradict theoretical predictions or methodological applications fail to produce expected findings, the entire paradigm faces fundamental challenges.

#### [Paradigm](chapter14.qmd#def-paradigm)
The term paradigm refers to “the set of common beliefs and agreements shared between scientists about how problems should be understood and addressed” [@kuhn1962structure]. Paradigms reflect the assumptions associated with the state-of-affairs. In the experimental context, these assumptions directly shape the methodological strategies employed to address a research question and influence the interpretation of empirical findings.

#### [P-Hacking](science.qmd#def-phacking)
P-Hacking is the practice of manipulating data analysis until non-significant results (p > .05) become statistically significant (p < .05).



#### [Positive-Negative Asymmetry Effect](chapter9.qmd#def-pnae)
Individuals tend to discriminate more when given positive outcomes (e.g., money or points) than when given negative outcomes (e.g., fines).


#### [Power Analysis](chapter6.qmd#def-poweranalysis)
A power analysis is used in research to estimate the probability that an effect, if it does exist, could be found in the data given. Usually, a power analysis is conducted to estimate the minimum sample size needed to detect a certain effect before running the study (a priori).

#### [Precognition or Premonition](chapter6.qmd#def-precognition)
The conscious cognitive awareness or affective apprehension of a future event that could not otherwise be anticipated through any known inferential process [@bem_feeling_2011].

#### [Prejudice](chapter12.qmd#def-prejudice)
A negative attitude toward a group and its members, often based on stereotypes rather than direct experience.

#### [Pre-registration](chapter6.qmd#def-preregistration)
The process of formally specifying the hypotheses, methods, and planned analyses of a study before any data is collected or examined. Preregistration distinguishes genuine predictions from post hoc explanations, fosters transparency, and increases the credibility and interpretability of research findings [@NosekEbersoleDeHavenMellor2018; @van_den_akker_preregistration_2023].

#### [Pre-registration](chapter11.qmd#def-preregistration)
Pre-registrations are documents outlining the research plan (materials, analyses) and hypotheses prior to the research being conducted.



#### Priming ([Florida Priming Effect](chapter19.qmd#def-priming), [Hot Coffee Effect](chapter20.qmd#def-priming))
A psychological phenomenon where exposure to one stimulus (e.g., a word, image, or idea) influences how you respond to a later stimulus, often without conscious awareness.

#### [Priming](chapter6.qmd#def-priming)
Priming refers to the effects of a subtle cue on future behavior. The primed stimulus works by activating related concepts and making them easier to access. Typical priming techniques include the very short exposure of participants to a visual, auditory, olfactory, or haptic cue. For instance, presenting the word “lion” may lead to faster categorization of the word “cat” because the two concepts represent the same “animal” category.

#### [Priming]({chapter18.qmd#def-priming)
“Priming refers to facilitative effects of an encounter with a stimulus on subsequent processing of the same stimulus (direct priming) or a related stimulus (indirect priming)" [@tulving_priming_1982, 336].


#### [Prosocial Behavior](chapter13.qmd#def-prosocialbehavior)
Behavior where people help others, even at a cost to themselves.

#### [Prosocial Behavior](chapter14.qmd#def-prosocial)
Prosocial behavior refers to the voluntary actions aimed at benefiting others, including sharing, helping, and confronting [@eisenberg_prosocial_1998].

#### [Psychological Reactance](chapter4.qmd#def-psychologicalreactance)
Psychological reactance states that individuals have certain freedoms with regard to their behaviour. If these behavioural freedoms are reduced or threatened with reduction, the individual will be motivationally aroused to regain them.

#### [Publication Bias](science.qmd#def-publicationbias)
Publication Bias is the tendency for journals to publish only "positive" results (studies where something happened) while ignoring "null" results (studies where nothing happened).

#### [Publication Bias](chapter6.qmd#def-publicationbias)
Refers to distortions in which publications with significant results are more likely to be published than studies with non-significant results.

#### [Publication Bias](chapter11.qmd#def-publicationbias)
The phenomenon that research findings are more likely to be published when the results are statistically significant.



#### [Public Goods Game](chapter14.qmd#def-pgg)
Public Goods Games (PGG) refer to multi-player experimental scenarios in which individuals are required to suppress selfish behavior and cooperate to attain a mutually beneficial outcome. In this design, individuals can choose to voluntarily contribute to a common pool that will be multiplied and equally distributed across all group members. Individuals who do not contribute may free-ride on the contribution of cooperators which imposes the risk of exploitation. Although avoiding contribution is commonly rewarded in PGG, if the number of defectors is large no collectively beneficial outcomes are achieved [@gomez-gardenes_evolutionary_2011; @tomassini_public_2020].


#### [Pygmalion Effect](chapter2.qmd#def-pygmalioneffect)
The phenomenon in which higher expectations from others lead to improved performance.

#### [Questionable Research Practices (QRPs)](science.qmd#def-qrps)
Questionable research practices are actions that fall into a "grey area" between honest errors and outright fraud. They are often described as "p-hacking" or "data dredging" methods used to make a study's results look more significant or consistent than they actually are.


#### [Questionable Research Practices (QRPs)](chapter6.qmd#def-questionableresearchpractices)
Unethical behaviors in research which produce unreliable results and reduce the validity of the findings.



#### [Reflective Behavior](chapter14.qmd#def-reflectivebehavior)
Reflective behavior is supported by “System 2” and relies on effortful and slow mental operations that are deliberately controlled through reason (Kahneman, 2002).

#### [Registered Report](chapter11.qmd#def-registeredreport)
A publishing format where peer review comes before researchers conduct the study. Research first submit Introduction and Method sections, alongside the detailed hypotheses and plan of data analysis to test them. Only after this phase (Stage 1 Registered report) is reviewed and accepted, researchers start collecting the data and write the full report (Stage 2). This ensures that theoretically valuable and methodologically sound research is published regardless of the results.


#### [Replication](howto.qmd#def-replication)
An attempt to find the same result as a previous study in a new data set.

#### [Replication](science.qmd#def-replication)
Replication involves repeating a study using the same methods and sample size to see whether the results hold up. Replications help identify which findings are reliable and support the self-correcting nature of science.



#### Representativity or Representativeness ([Florida Priming Effect](chapter19.qmd#def-representativity), [Hot Coffee Effect](chapter20.qmd#def-representativity))
The extent to which a study sample reflects a well-defined target population, such that the estimates or the interpretation of results can be generalized to that population [@rudolph_defining_2023].

#### [Responsible Research Practices (RRPs)](science.qmd#def-responsibleresearchpractices)
Practices that researchers or journals can do to increase the credibility, transparency, and reproducibility of scientific findings.


#### [Salience](chapter13.qmd#def-salience)
Salience describes the characteristic of a stimulus to stand out. For instance, a word printed in red is visually salient in a text otherwise printed in black and white: it stands out.

#### [Selection Bias](chapter10.qmd#def-selectionbias)
Selection bias occurs when the participants selected for the study are not representative of the wider population, which can distort the research findings.

#### [Self-Fulfilling Prophecy](chapter19.qmd#def-selffulfillingprophecy)
A self-fulfilling prophecy suggests that the probability of an event occurring can be increased solely by the expectation of that event [@merton_self-fulfilling_1948].

#### [Scientific Method](science.qmd#def-scientificmethod)
The universal, step-by-step logical framework that underlies all scientific inquiry. The scientific method is a defined, step-by-step process for investigating phenomena. It is a formalization of a generalized human problem solving process.

#### [Scientific Process](science.qmd#def-scientificprocess)
The specific methods and approaches (e.g., saw for the table or surveys) that scientists use based on their specific field and matter. Various methods and approaches scientists use to investigate phenomena in their pursuit of knowledge.


#### [Social Comparison Theory](chapter8.qmd#def-socialcomparisontheory)
According to the social comparison theory, people are motivated to assess their own beliefs and skills by comparing them to external images. These images can be comparisons to other people or a reference to physical reality. Individuals have a tendency to view images portrayed by others as accessible and realistic and subsequently make comparisons between themselves, other people, and these idealized images.

#### [Social Desirability](chapter15.qmd#def-socialdesirability)
The tendency to want to be viewed positively by others, often by aligning with socially approved behaviors and attitudes.

#### [Socially Desirable Responding](chapter15.qmd#def-sociallydesirableresponding)
The act of providing inauthentic responses to better present oneself favorably according to current social norms.

#### [Social Dilemma](chapter14.qmd#def-socialdilemma)
Social dilemmas refer to a set of scenarios in which individual and collective interests are mutually exclusive, yielding a conflict between selecting strategies that increase personal over collective benefits. Although selfish decisions are typically rewarded, personal gains are reduced if a substantial number of individuals aim for maximum gains [@APA-dict_2018].

#### [Social Dominance Orientation](chapter9.qmd#def-sdo)
The belief that society should be organized hierarchically, which endorses hierarchy and legitimizes myths such as sexism, racism, classism, etc.

#### Social Group ([Minimal Group Effect](chapter9.qmd#def-socialgroup), [Stereotype Threat](chapter11.qmd#def-socialgroup))
A social group consists of two (often called a dyad) or more individuals who depend on each other and influence each other through their social interactions.

#### [Social Heuristics Hypothesis](chapter14.qmd#def-socialheuristic)
A dual-process theoretical framework illustrating that social decision-making lies on internalized strategies that are considered advantageous in social encounters. People employ these intuitive responses in typical and atypical contexts. Under uncertain conditions, automatic responses may be overridden by effortful and evaluative processing that yields context-appropriate responses [@rand_spontaneous_2012].

#### [Social Loafing](chapter7.qmd#def-socialloafing)
Social loafing or the Ringelmann effect refers to the decrease in individual effort that occurs when people work as part of a group rather than independently.

#### [Social Norm](chapter22.qmd#def-socialnorm)
A social standard that enables the evaluation of behaviors as appropriate or inappropriate within a specific context.

#### [Special Issue](chapter2.qmd#def-specialissue)
A collection of articles on a specific topic, typically published together in a single issue of an academic journal. Special issues are often edited by guest editors and aim to provide a comprehensive exploration of the chosen theme or field of study.

#### [Statistical Power](science.qmd#def-statisticalpower)
Statistical power is the probability that a study will detect an effect (a real relationship) if that effect actually exists.


#### [Stereotype](chapter11.qmd#def-stereotype)
Stereotypes are beliefs about people held because of their membership in a social group.

#### [Stereotype](chapter19.qmd#def-stereotype)
A belief about characteristics of people belonging to a certain social group, attributed to them because of their group membership.

#### [Stereotype Threat](chapter11.qmd#def-stereotypethreat)
Stereotype threat refers to an individual’s fear that their own characteristics or behaviors could confirm negative stereotypes about their group.

#### [Subliminal](chapter6.qmd#def-subliminal)
Subliminal refers to the exposure of stimuli for such a short amount of time that humans are not aware of the stimuli perceived and therefore cannot actively process the information.

#### Treatment and Control Conditions ([Stereotype Threat](chapter12.qmd#def-treatmentandcontrolconditions), [Hot Coffee Effect](chapter20.qmd#def-treatmentandcontrolconditions))
In experimental design, treatment condition refers to the participants who are randomly chosen to undergo the intervention (e.g., to play in the mixed soccer team). Control condition refers to the participants who are subject to intervention-like treatment that lacks the critical aspect of the intervention (e.g., those allocated to play in the all-Christian soccer team). Here, the critical aspect is intergroup contact within the team.

#### [Trust](chapter24.qmd#def-trust)
An attitude toward others – other persons, groups of persons, and institutions – in which there is (a) an expression of vulnerability to that other, and (b) a belief that the other has the ability, the willingness, and will act in ways that benefit us in light of that vulnerability as opposed to taking personal advantage of it.

#### [Trust Game](chapter24.qmd#def-trustgame)
An experimental task used to measure interpersonal trust, in which one participant receives an initial endowment and decides how much to send to another participant. The amount sent is increased by the experimenter, and the second participant then chooses how much to return if at all. The initial transfer is interpreted as reflecting trust, as it involves risking resources under uncertainty about the other’s behavior, while the returned amount is interpreted as reflecting trustworthiness as the participant chose to return the endowment that they could have easily kept for themselves.

#### [Type I Error / Alpha Error / False Positives](chapter6.qmd#def-typeIerror)
Inferring from a statistical test that a certain effect exists, although it does not exist in reality.

#### [Tyranny](chapter10.qmd#def-tyranny)
Tyranny refers to a system of unequal power in which one group or its representative use authority in an arbitrary or oppressive way over another group.

#### [WEIRD](science.qmd#def-WEIRD)
An acronym for people from Western, Educated, Industrialized, Rich, and Democratic (WEIRD) backgrounds. When relying on samples of WEIRD participants, scientists are looking at a unique subgroup that does not represent the general population. This makes it difficult to claim that these findings are universal truths about human nature.

#### [Working Memory](chapter11.qmd#def-workingmemory)
Working memory refers to a part of human cognitive functioning that temporarily stores information and holds available to be "worked with".


#### [Zygomaticus Major Muscles](chapter17.qmd#def-zygomaticusmajormuscles)
These bilateral facial muscles, when activated, raise the corners of the mouth in an upward and lateral direction, facilitating expressions such as smiling.
