# [Introduction]{style="color: #004b23"} {.unnumbered}

[written by Rima-Maria Rahal]{style="color: gray;"}

## The Role of Change for Scientific Discovery

Much of science capitalizes on change. It is the engine that drives progress and the expansion of knowledge [see @kuhn1962structure; @popper1959logic]. Embracing change means taking established theories and challenging them to explore new directions. Changing perspectives, questioning the status quo, refining existing concepts, and adapting to new evidence provide the stuff that makes breakthroughs or new insights. In essence, change in science represents taking steps forward, toward greater insight and reality checks for the challenges we face. In other words, to push the boundaries of what we know, we must make change.

> [#yourturn]{style="color: green"}
>
> What instance of change regarding science have you recently heard about? Consider reports of breakthroughs you might have seen in the news or stories you saw on social media.

In the past decade, Open Science has made change, by transforming research practices to promote transparency, reproducibility, and collaboration in scientific endeavors. By fostering a culture of openness and collaboration, Open Science has brought about a paradigm shift in research methodologies, paving the way for more robust and reliable scientific discoveries [@munafo2017manifesto; @vazire2022credibility]. It is certainly no small feat to fundamentally reform how research is done, and yet we have seen significant change towards Open practices [@kidwell2016badges; @chambers2019registered; @christensen2020open].

> [#definition]{#def-openscience style="color: orchid"} Open Science
>
> An overhead term for a number of practices to make research more transparent, such as making the data a research project is based on available to others.

## Challenges of Making Change

Change can be a challenge because it disrupts established norms, habits, and power structures. This often means that individuals and groups might be hesitant to embrace change. Open Science, as a reform to refocus on good research practice, had to work with this difficulty of making change, where new methods, theories, or technologies often encounter skepticism and opposition from the scientific community. Open Science promotes transparency, data sharing, and collaborative research, which can expose flaws underlying previously held beliefs or reveal alternative interpretations. This shift can create debates about long-held ideas and established practices, which are scrutinized and potentially overturned. Established researchers may be reluctant to abandon familiar paradigms, and institutions may resist reallocating resources or altering well-known processes. Sometimes, inertia of traditional practices and fear of uncertainty can slow the adoption of innovative approaches, despite their potential to advance knowledge and solve pressing problems. 

> [#yourturn]{style="color: green"}
>
> Consider a big change you have experienced. Was it easy to adapt to this change?

However, a questioning attitude and focus on methodological rigor and good practice also enhance the robustness and reliability of scientific conclusions by fostering an environment where continuous re-evaluation is encouraged. Thus, Open Science exemplifies how embracing change can lead to a more dynamic and resilient understanding of the world, even as it unsettles the familiar foundations of scientific consensus.

Change often implies the potential for a changed perception of what used to be, particularly in comparison to what is now. This is also the case in the scope of changes associated with Open Science. In particular, what were once considered unassailable facts can become contested or uncertain as new methodologies, data, and technologies challenge established knowledge. This is where our focus lies in this book: reporting on classical studies in social psychology and the change in how they are seen now, following a wave of additional research (often with an Open Science flavor). 

> [#yourturn]{style="color: green"}
>
> "I was today years old when I found out ..." What was the last long-held belief you had to give up?  

In this spirit, when reading about the changes in perspective about classics in social psychology, there are two things to embrace: 

On the one hand, revisiting classic social psychology studies is a demonstration of the profound impact they had on the field. Were they less important and less impactful, these studies would not draw continued debate, research interest and investment of resources. Therefore, reading classic studies can give readers a sense of what matters to social psychological research, from hot topics to hot paradigms and research methods.  

On the other hand, following the course of the academic debate about these claims, insights and phenomena allows us to hone our skills in accumulating insights and adjusting our perception of the currently held beliefs in this area of research. Put differently, tracing efforts to replicate, to conduct meta-analyses or to establish boundary conditions to the findings postulated in a certain study mostly reflects well-intentioned interest in assessing the validity of the claims of the original study, attempting to produce clarity about our collective knowledge about the phenomenon of interest. Reassessing classical studies might require change in opinions, calibration and reflection, but it can surely spark renewed trust in research and in its ability to refine and build our joint knowledge. 

## Stories of Change in this Book

This book contains more than 20 stories of change in psychological science. We have compiled these stories from across the spectrum of topics that social psychology addresses. Clustering these themes broadly, the chapters included here address three major research trajectories. 

The first part of this book addresses research that is at the very core of social psychological inquiry. It addresses both classic questions of how we perceive our (social) environment and how our social perception comes into being. The research contained within asks questions such as "Can people predict the future?" (Chapter on [Feeling the Future](chapter6.qmd)), "Can believing in someone's success make them more successful?" (Chapter on the [Pygmalion Effect](chapter2.qmd)), or "Can humans run out of self-control?" (Chapter on [Ego Depletion](chapter5.qmd)). 

The second part of this book dives deeper into research addressing how the social context changes how humans behave. The presence of others, as well as our embeddedness in social groups exerts a strong pull on what individuals will do. The research covered in this part of the book is concerned with demonstrating this social influence on behavior. It asks questions such as "When will people blindly follow the example of others?" (Chapter on [Conformity](chapter21.qmd)), and "Why do people obey orders?" (Chapter on [Obedience to Authority](chapter4.qmd)). Another facet of this research focuses on the influence of social roles and norms. It asks whether stepping into a social role such as that of a prisoner or a prison guard will make us change our behavior (Chapter on the [Stanford Prison Experiment](chapter10.qmd)) and whether we litter more when we see evidence that others do so, too (Chapter on [Social Norms](chapter22.qmd)). This research also addresses the particular influence of the groups we belong to on our behavior. It asks whether we treat members of our team better than members of a rivaling group even if group membership is arbitrary (Chapter on the [Minimal Group Effect](chapter9.qmd)) and how conflicts between groups can be mitigated (Chapter on [Intergroup Contact Theory](chapter12.qmd)). Finally, this part of the book also addresses research that is focused on a particular type of behavior in the social context: helping others (prosociality). This research investigates when humans will step in to help, and when the mere presence of others makes us hang back to wait if someone else will help (Chapter on the [Bystander Effect](chapter13.qmd)). This research is also concerned with whether helping is an intuitive human behavior, or if it requires us to override selfish impulses (Chapter on the [Social Heuristics Hypothesis](chapter14.qmd)).

In the third part of the book, we have compiled research that addresses how social contexts shape the way we think, the attitudes and beliefs we hold (and the consequences for behavior). For example, research covered in this part of the book addresses the question whether being exposed to warmth may lead us to perceive others as warmer and friendlier (Chapter on the [Hot Coffee Effect](chapter20.qmd)), or whether thinking about words stereotypically related to old age will make us adopt behaviors assosciated with older age (Chapter on the [Florida Priming Effect](chapter19.qmd)).

The chapters begin aiming to demonstrate where a certain research question came from. They then identify a classic study that addressed this research question, and assess it in detail. The chapters then outline the response in the field, including follow-up studies and replication attempts by other researchers, as well as meta-analytic evidence addressing the same research question. Finally, these chapters reflect on if and how our knowledge about the research question, and potentially our interpretation of the evidence may have changed. 

Because understanding such change in scientific insight is no small feat, this book prepends a [chapter](science.qmd) dedicated to explaining how the stories of change described later on can be reconciled with the idea that science is dedicated to discovering general laws and robust insights. This chapter outlines the scientific method and explains where in the research process things can go awry, leading to findings with limited replicability and reproducibility. It also explains how responsible research practices can help strengthen the robustness of research. Most importantly, however, this chapter explains in more detail how and why change is part of the natural process of gathering scientific insight. 


